### ISSUE TITLE
Constant variable not being created

### ISSUE THREAD

**Issue by sike417** [sike417/LightReader#1]
JavaScript runtime error: Unable to get property 'LIST_URL' of undefined or null reference is thrown on the line where MediaParser.ts tries to access the Constant variable

**Comment by sike417** [comment]
Issue solved was not invoking constant.js within index. Intentional?

**Comment by Masclaux** [comment]
Hi.

You don't have fix issue with your commit and is not even an issue.  

You forget to execute gulp file "gulpfile.js" who auto include all necessary files.

See capture below ( you can add autoexecute with right click on "auto_include" ).

![capture](https://cloud.githubusercontent.com/assets/11290292/12074272/d26e73c8-b149-11e5-894c-ed153273a338.PNG)

You cannot modify index.html and javascript files their are generated by compiler modify only index.tpl.html ans *.ts files .
